### ISSUE TITLE
Getting an Error at Step 10

### ISSUE THREAD

**Issue by pjockey** [kshetline/aw-clock#103]
```
- Dedicated device setup -
Step 1 of 17: Updating/upgrading packages (can take a long time!) ✔
Step 2 of 17: Stopping weatherService if currently running ✔
Step 3 of 17: pigpio already installed ✔
Step 4 of 17: chromium-browser already installed ✔
Step 5 of 17: unclutter already installed ✔
Step 6 of 17: Installing forever ✘
Step 7 of 17: Fonts already installed ✔
Step 8 of 17: xscreensaver already installed ✔
Step 9 of 17: Disabling screen saver ✔
- Building application -
Step 10 of 17: Updating client ✘
ERROR: npm v10.2.3 is known not to run on Node.js v12.22.12.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/usr/local/lib/node_modules/npm/lib/utils/exit-handler.js:19
  const hasLoadedNpm = npm?.config.loaded
                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:15:23)
    at module.exports (/usr/local/lib/node_modules/npm/lib/es6/validate-engines.js:39:10)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:4:31)

```
I'm not sure what I missed here. The npm version said 6 and nodejs was 12.

**Comment by pjockey** [comment]
I gave up trying to get this to work. It appear the npm and nodejs versions don't like each other. I tried to install ones that would work together, but had the same problem after doing  the `sudo ./build.sh -i `command.

**Comment by kshetline** [comment]
I've made changes in the latest release in how Node.js is updated, and what versions are accepted, which should clear all of this up. Sorry it took so long for me to ever see any similar problems myself so that I could get a handle on what to change.
