### ISSUE TITLE
Installer thinks it's not an RPi?

### ISSUE THREAD

**Issue by codevbus** [kshetline/aw-clock#49]
I'm getting this error when attempting to install:

```
--ddev option is only valid on Raspberry Pi
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aw-clock@2.9.1 build:prod: `ts-node build.ts -p "--bash" "--ddev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aw-clock@2.9.1 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-14T23_23_40_087Z-debug.log
```
Contents of the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod',
1 verbose cli   '--',
1 verbose cli   '--bash',
1 verbose cli   '--ddev'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v12.21.0
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle aw-clock@2.9.1~prebuild:prod: aw-clock@2.9.1
6 info lifecycle aw-clock@2.9.1~build:prod: aw-clock@2.9.1
7 verbose lifecycle aw-clock@2.9.1~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle aw-clock@2.9.1~build:prod: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/build/aw-clock/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle aw-clock@2.9.1~build:prod: CWD: /home/pi/build/aw-clock
10 silly lifecycle aw-clock@2.9.1~build:prod: Args: [ '-c', 'ts-node build.ts -p "--bash" "--ddev"' ]
11 silly lifecycle aw-clock@2.9.1~build:prod: Returned: code: 1  signal: null
12 info lifecycle aw-clock@2.9.1~build:prod: Failed to exec build:prod script
13 verbose stack Error: aw-clock@2.9.1 build:prod: `ts-node build.ts -p "--bash" "--ddev"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid aw-clock@2.9.1
15 verbose cwd /home/pi/build/aw-clock
16 verbose Linux 4.19.66-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:prod" "--" "--bash" "--ddev"
18 verbose node v12.21.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error aw-clock@2.9.1 build:prod: `ts-node build.ts -p "--bash" "--ddev"`
22 error Exit status 1
23 error Failed at the aw-clock@2.9.1 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kshetline** [comment]
There are two things the installer checks to determine if your hardware is Raspberry Pi. One thing is the contents of `/proc/cpuinfo`:

```text
pi@clock:~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: b03111
Serial		: 100000000499a5aa
Model		: Raspberry Pi 4 Model B Rev 1.1
```

...with the important part being that last line, where it looks for the words "model", "raspberry", and "pi".

The second thing it seconds is where Node.js reports `process.platorm` as "linux". It sounds like the installer got at least as far as installing node, so you chould be able to check this too:

```
pi@clock:~ $ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> process.platform
'linux'
> .exit
pi@clock:~ $ 
```

What results do you get?

**Comment by codevbus** [comment]
Results for both:

```
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 000000006389a9d2
```

**Comment by kshetline** [comment]
That's very weird that your cpuinfo file doesn't have the Raspberry Pi model at the end. Which Raspberry Pi is it?

**Comment by codevbus** [comment]
```
pi@officerpi:~ $ cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Rev 1.2
```

**Comment by kshetline** [comment]
I'll update my installer to make the criteria for identifying a Raspberry Pi more flexible. I only have two models to test myself, and the other is a 3B Plus, which also lists the model in cpuinfo.

**Comment by codevbus** [comment]
Awesome! Thank you.

Maybe the value in `/sys/firmware/devicetree/base/model` is a more reliable indicator?

**Comment by kshetline** [comment]
It could be. I'm going to use both now, together.

**Comment by kshetline** [comment]
You can pull the latest update now. Let me know if it works for you.

**Comment by codevbus** [comment]
So that definitely got me past the primary issue, however I'm hitting OOM errors:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by codevbus** [comment]
Got past the OOM error.

**Comment by kshetline** [comment]
Full working installation yet?

**Comment by codevbus** [comment]
Yep! Managed to complete the install, rebooted and have a functional clock. Good to close.

Thanks so much for your responsiveness and hard work. Really love the clock so far!
