### ISSUE TITLE
Error installing from scratch

### ISSUE THREAD

**Issue by Aymendje** [kshetline/aw-clock#66]
I have a fresh copy of raspbian, and when running `sudo ./build.sh -i` I am getting an npm error (seems some packages are mismatched versions ?)

```
Installing npm packages. This process can be very slow!
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 529 packages, and audited 530 packages in 7m

65 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: aw-clock@2.12.2
npm ERR! Found: webpack@5.67.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.47.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from istanbul-instrumenter-loader@3.0.1
npm ERR! node_modules/istanbul-instrumenter-loader
npm ERR!   dev istanbul-instrumenter-loader@"^3.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/pi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-22T00_47_20_046Z-debug.log
Starting main installer...
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@tubular/util'
Require stack:
- /home/pi/tools/aw-clock/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.483 (/home/pi/tools/aw-clock/build.js:85:146)
    at __webpack_require__ (/home/pi/tools/aw-clock/build.js:86:316)
    at Object.582 (/home/pi/tools/aw-clock/build.js:3:231)
    at __webpack_require__ (/home/pi/tools/aw-clock/build.js:86:316)
    at /home/pi/tools/aw-clock/build.js:86:395
    at Object.<anonymous> (/home/pi/tools/aw-clock/build.js:86:402) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/tools/aw-clock/build.js' ]
}
```

**Comment by kshetline** [comment]
I haven't had a chance to try this on a clean Pi yet, but I'll let you know what happens as soon as I can.

**Comment by kshetline** [comment]
I wasn't able to reproduce your problem. This is what I got starting from a fresh git clone:

```
pi@raspberrypi:~ $ git clone https://github.com/kshetline/aw-clock.git
Cloning into 'aw-clock'...
remote: Enumerating objects: 2058, done.
remote: Counting objects: 100% (434/434), done.
remote: Compressing objects: 100% (313/313), done.
remote: Total 2058 (delta 298), reused 212 (delta 121), pack-reused 1624
Receiving objects: 100% (2058/2058), 26.03 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (1543/1543), done.
pi@raspberrypi:~ $ cd aw-clock/
pi@raspberrypi:~/aw-clock $ sudo ./build.sh -i
Checking installation pre-requisites...
Installing npm packages. This process can be very slow!
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 861 packages, and audited 862 packages in 1m

110 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (3 low, 2 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 8.2.0 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
Starting main installer...
- GPS test -
GPS time and/or location services not found
The following updates/changes are suggested if GPS support is desired:
  • Install gpsd and gpspipe
  • Install ntpd and ntpq
  • Install ppstest
- Configuration -
Perform initial update/upgrade? (Y/n): 
```
I tested this out on an old RP 3B with 1 GB RAM. It has node 12.22.7 and npm 8.2.0 installed.

**Comment by Aymendje** [comment]
Weird
I also have a RBP 3B
Thank you, I will retry a new install !

**Comment by pidloop** [comment]
Just as another data point, I just installed on a clean bullseye and got the exact same errors. But on an older buster I had not problem at all. I took all the N options just to get it up without any fiddling and it took about 20 minutes on my 1GB Pi4. But it was well worth it -- fantastic program -- absolutely beautiful. Puts my little [HamClock](https://clearskyinstitute.com/ham/HamClock) to shame. Many thanks.

**Comment by kshetline** [comment]
Since I wasn't actually using istanbul-instrumenter-loader, or the related karma/jasmine testing suite (bad, bad, naughty programmer!) I've decided to strip those packages out. Given that this project is supposed to build on a Raspberry Pi, the smaller the footprint, the better. These changes should hopefully prevent build errors, such as those the two of you encountered, in the next release.

**Comment by Aymendje** [comment]
Hello ! 
Thank you so much for the quick update !
I synced the latest from master and now it works for me !
